#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOCS_DIR="$REPO_ROOT/docs"
COUNTRIES_DIR="$REPO_ROOT/countries"
OUTPUT_FILE="$REPO_ROOT/full/gdpr-compliance-guide.md"

TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")

# Start with header
cat > "$OUTPUT_FILE" << EOF
# GDPR Compliance Guide

> **Disclaimer:** This document is for informational purposes only and does not constitute legal advice. The authors and contributors assume no liability. Always verify with a qualified legal professional. See the project [DISCLAIMER](../DISCLAIMER.md) for full details.

> **Generated:** $TIMESTAMP — Do not edit this file directly. Edit the source files in \`docs/\` and \`countries/\` and run \`scripts/build.sh\`.

> **License:** [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

---

EOF

# Append docs in order
for doc in "$DOCS_DIR"/[0-9]*.md; do
  [ -f "$doc" ] || continue
  # Strip the disclaimer header line (single line starting with "> **Disclaimer:**")
  sed '/^> \*\*Disclaimer:\*\*/d' "$doc" >> "$OUTPUT_FILE"
  printf "\n\n---\n\n" >> "$OUTPUT_FILE"
done

# Add country separator
cat >> "$OUTPUT_FILE" << 'EOF'
# Country-Specific Requirements

The following sections contain requirements specific to individual EU/EEA member states. These supplement the EU-wide requirements above with national transposition laws, DPA provisions, and local case law.

---

EOF

# Append country files (excluding template), sorted alphabetically
for country in "$COUNTRIES_DIR"/[!_]*.md; do
  [ -f "$country" ] || continue
  sed '/^> \*\*Disclaimer:\*\*/d' "$country" >> "$OUTPUT_FILE"
  printf "\n\n---\n\n" >> "$OUTPUT_FILE"
done

echo "Built: $OUTPUT_FILE"
